### ISSUE TITLE
Plugin Build fails

### ISSUE THREAD

**Issue by rofoto** [Naragato/Mqttify#5]
I get this error when trying to build the plugin in UE 5.4.4 using C:\Program Files\Epic Games\UE_5.4\Engine\Build\BatchFiles\RunUAT.bat

```
C:\Program Files\Epic Games\UE_5.4\Engine\Source\Runtime\Core\Public\GenericPlatform\GenericPlatformProcess.h(800): error C2062: type 'void' unexpected

C:\Program Files\Epic Games\UE_5.4\Engine\Source\Runtime\Core\Public\GenericPlatform\GenericPlatformProcess.h(801): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
```
It seems there is an issue with these files

[55/63] Compile [x64] MqttifyTopicFilter.cpp
[56/63] Compile [x64] MqttifySocket.cpp

Any help would be much appreciated.

log attached below:
[BUILD_FAIL_UBA-UnrealGame-Win64-Development.txt](https://github.com/user-attachments/files/17533568/BUILD_FAIL_UBA-UnrealGame-Win64-Development.txt)

**Comment by Naragato** [comment]
NMI. Your build args and uproject setup at least.

Also it's worth using

`C:\Program Files\Epic Games\UE_5.4\Engine\Build\BatchFiles\Build.bat HostProject Win64 Development -Project="G:\00_3D_SELF_PROJECTS_2024\17_PROJECT_IN_UNREAL\PROJECT_UNREAL\Plugins\Mqttify544\HostProject\HostProject.uproject " `

You shouldn't need any more args to load the plugins (realistically the should be enabled in the uproject).

But some observations from the logs.

`G:\00_3D_SELF_PROJECTS_2024\17_PROJECT_IN_UNREAL\PROJECT_UNREAL\Plugins\Mqttify544\HostProject\`  Why is the plugin here?  Shouldn't matter for this case, but seems strange

**Comment by rofoto** [comment]
> NMI. Your build args and uproject setup at least.

"RunUAT.bat BuildPlugin -plugin="G:\00_3D_SELF_PROJECTS_2024\17_PROJECTNAME\TOOLS\Mqttify-main\Mqttify.uplugin" -package="G:\00_3D_SELF_PROJECTS_2024\17_PROJECTNAME\TOOLS\Mqttify-main544"

the uproject has never been modified by me, this is the first time I am trying a community plugin that required a rebuild

uproject listing below:
```{
	"FileVersion": 3,
	"EngineAssociation": "5.4",
	"Category": "",
	"Description": "",
	"Plugins": [
		{
			"Name": "ModelingToolsEditorMode",
			"Enabled": true,
			"TargetAllowList": [
				"Editor"
			]
		},
		{
			"Name": "ElectraPlayer",
			"Enabled": true
		},
		{
			"Name": "HoudiniEngine",
			"Enabled": true
		},
		{
			"Name": "CineCameraSceneCapture",
			"Enabled": true
		}
	],
	"TargetPlatforms": [
		"Windows"
	]
}```

I have also seen that having houdini engine installed breaks builds but I have tested the RunUAT build command with your plugin with and and without houdini engine installed and both do not seem to work.

Any help would be great. I am in the process of building UE from source in hopes that this makes it possible to use the plugin.

**Comment by rofoto** [comment]
UPDATE,

I had to rearrange the plugins files as shown in the zip file attached below:
[Mqttify_REPACK.zip](https://github.com/user-attachments/files/17535913/Mqttify_REPACK.zip)

and using these directions from Epic Games site: [](https://dev.epicgames.com/community/learning/tutorials/qz93/unreal-engine-building-plugins)

```
Using The Editor:
1 Create an empty C++ project with the Engine version you wish to use.
     -Bring the plugin(s) to that C++ project
     -Create a "Plugins" folder in the C++ project's root folder.

2 Copy the plugin(s) folder(s) you want to build into the newly created "Plugins" folder.
      -Manually delete the “Intermediate” and “Binaries” folders of the plugin(s).
      - Double-click on your .uproject file to relaunch the Editor. You should see a popup telling you that some modules need to be rebuilt.   Click Accept.  This should rebuild your plugin(s).

Once done, copy the plugin from the compiled C++ project to the Engine's plugins folder, and overwrite any conflicting files.
```

doing this got the plugin to build. Maybe the zip file and directions I provided could be used as the 'release' version so that others can more easily build the plugin.

**Comment by Naragato** [comment]
This is the process for all UE plugins build from source.  I don't intend to add the plugin to FAB either atm.
